# UPBIT
UPBIT_ACCESS_KEY : "TQcHNv10q7AG2FxSkEhadyQNmf7JEvVmhmoTqQzV"
UPBIT_SECRET_KEY : "Pywp6HfRHcXqoRGcJRQZKF9C2FTGBekCZWQpKk0R"


# BINANCE
BINACE_APT_KEY : "WYWam2SvnZCDK3rk33Dy50EXdbcZzkgj0uudrQawQquNDU0rveMxpT9vZVozr6H5"
BINACE_SECRET_KEY : "KdvSmsPX5D34kq6DLqHJqO3Sg6DFnG7UFxN4K7JGVEni7zwyPfROYeI4uzA5WmQj"


# DISCORD
DISCORD_BOT_TOKEN : "MTIxMzA3MTExNjU3MTI1MDcyOA.GgBwpV.hGA3iFQchP8_S0vfBv3grOjLNqTgyjac1wbVUY"
